# Generated by Django 5.0 on 2026-01-08 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('preferred_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences_received', to='students.studentprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences_made', to='students.studentprofile')),
            ],
            options={
                'ordering': ['rank', 'created_at'],
                'unique_together': {('student', 'preferred_student')},
            },
        ),
    ]
