# Generated by Django 5.0 on 2026-01-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_studentpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='enrollment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
