# Generated by Django 5.0 on 2026-01-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_studentprofile_enrollment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='teams_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='is_solo',
            field=models.BooleanField(default=False),
        ),
    ]
