# Generated by Django 5.0 on 2026-01-22 07:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_studentprofile_students_st_student_58f688_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='allow_solo_projects',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cohort',
            name='auto_matching_strategy',
            field=models.CharField(choices=[('balanced', 'Equal-sized teams'), ('preference_based', 'Honor student preferences'), ('fill_existing', 'Fill incomplete teams first')], default='balanced', max_length=20),
        ),
        migrations.AddField(
            model_name='cohort',
            name='max_team_size',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='cohort',
            name='min_team_size',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='cohort',
            name='team_formation_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='assignment_status',
            field=models.CharField(choices=[('unassigned', 'Unassigned'), ('in_team', 'In Team'), ('solo_assigned', 'Solo Assigned'), ('opted_out', 'Opted Out')], default='unassigned', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='seeking_team',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='team',
            name='creation_method',
            field=models.CharField(choices=[('manual_student', 'Student Formed'), ('manual_admin', 'Admin Formed'), ('auto_matched', 'Auto Matched'), ('solo_assignment', 'Solo Assignment')], default='manual_student', max_length=20),
        ),
        migrations.AddField(
            model_name='team',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='is_solo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='status',
            field=models.CharField(choices=[('forming', 'Forming'), ('complete', 'Complete'), ('locked', 'Locked'), ('solo', 'Solo')], default='forming', max_length=20),
        ),
        migrations.AddField(
            model_name='team',
            name='target_size',
            field=models.IntegerField(default=5),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['seeking_team'], name='students_st_seeking_ced3fe_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['assignment_status'], name='students_st_assignm_3f8aaa_idx'),
        ),
    ]
